"""create tasks table

Revision ID: b0c9603578e5
Revises: 
Create Date: 2025-11-11 11:50:38.234411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c9603578e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('expected_duration', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    tasks_table = sa.table(
        'tasks',
        sa.column('id', sa.Integer()),
        sa.column('name', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('difficulty', sa.String()),
        sa.column('expected_duration', sa.Integer()),
        sa.column('success_rate', sa.Float()),
        sa.column('thumbnail', sa.String()),
    )
    op.bulk_insert(
        tasks_table,
        [
            {
                'id': 1,
                'name': '桌面机械臂抓取',
                'description': '操控机械臂抓起目标方块并放入指定区域。',
                'difficulty': '新手友好',
                'expected_duration': 3,
                'success_rate': 72.5,
                'thumbnail': '/design/Task-Detail.png',
            },
            {
                'id': 2,
                'name': '滑轨推球',
                'description': '通过推杆控制，将钢球推到目标位置。',
                'difficulty': '中等',
                'expected_duration': 5,
                'success_rate': 52.1,
                'thumbnail': '/design/Task-Detail.png',
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
